"""add user

Revision ID: 1821c0926c02
Revises: ffbbed28db47
Create Date: 2023-02-12 17:26:20.018746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1821c0926c02'
down_revision = 'ffbbed28db47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'ln')
    op.drop_column('user', 'fn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ln', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
