"""refactoring user

Revision ID: 2688a78ffa5d
Revises: 1821c0926c02
Create Date: 2023-02-12 17:29:54.439964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2688a78ffa5d'
down_revision = '1821c0926c02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
