"""location table uniq

Revision ID: 3dd37d5f9e79
Revises: c0a13fe8d7d0
Create Date: 2023-02-14 11:51:54.609188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dd37d5f9e79'
down_revision = 'c0a13fe8d7d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('locations', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('locations_uniq_coord_key', 'locations', type_='unique')
    op.drop_column('locations', 'uniq_coord')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('uniq_coord', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('locations_uniq_coord_key', 'locations', ['uniq_coord'])
    op.alter_column('locations', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('my_table',
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', name='my_table_pkey')
    )
    # ### end Alembic commands ###
