"""location table unique

Revision ID: c0a13fe8d7d0
Revises: ab1b261948da
Create Date: 2023-02-14 01:33:36.982383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a13fe8d7d0'
down_revision = 'ab1b261948da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'locations', ['uniq_coord'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    # ### end Alembic commands ###
